TERMS_PRIORITARIOS = [
    "inflation",
    "price index",
    "CPI",
    "GDP growth",
    "economic growth",
    "unemployment",
    "consumer confidence",
    "interest rates",
    "central bank policy",
    "housing market",
    "ETF",
    "bonds",
    "portfolio strategy",
    "market sentiment",
    "AI fintech",
    "blockchain",
    "bitcoin",
    "ethereum",
    "quantitative finance",
    "algorithmic trading",
    "digital banking",
    "mobile wallets",
    "neobanks"
]